# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.
# Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_0:
    has_velocity_limits: true        # ✅ Enable velocity limits
    max_velocity: 2.0                # ✅ Set reasonable max velocity (rad/s)
    has_acceleration_limits: true    # ✅ Enable acceleration limits
    max_acceleration: 1.0            # ✅ Set reasonable max acceleration (rad/s²)
    has_position_limits: true
    max_position: 1.5707
    min_position: -1.5707
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_position_limits: true
    max_position: 1.5707
    min_position: -1.5707
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_position_limits: true
    max_position: 1.5707
    min_position: -1.5707
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_position_limits: true
    max_position: 1.5707
    min_position: -1.5707
  joint_4:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_position_limits: true
    max_position: 1.5707
    min_position: -1.5707
  joint_5:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_position_limits: true
    max_position: 1.5707
    min_position: -1.5707
  joint_7:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_position_limits: true
    max_position: 1.5707
    min_position: -1.5707
  joint_g:
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: true    # ✅ Added acceleration limits for gripper too
    max_acceleration: 5.0            # ✅ Set gripper acceleration