planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0
  PRMkConfigDefault:
    type: geometric::PRM
    range: 0.0

planning:
  allow_approximate_solution: true
  error_threshold: 0.05
  max_solution_time: 5.0
  max_goal_samples: 20
