planning_pipelines:
  ompl:
    planning_plugin: ompl_interface/OMPLPlanner
    request_adapters:
      # Order is important - these run in sequence!
      - default_planner_request_adapters/ResolveConstraintFrames
      - default_planner_request_adapters/ValidateWorkspaceBounds  
      - default_planner_request_adapters/CheckStartStateBounds
      - default_planner_request_adapters/CheckStartStateCollision
      - default_planner_request_adapters/FixWorkspaceBounds
      - default_planner_request_adapters/FixStartStateBounds
      - default_planner_request_adapters/FixStartStateCollision
      - default_planner_request_adapters/FixStartStatePathConstraints
      - default_planner_request_adapters/AddTimeOptimalParameterization  # Better than AddTimeParameterization
    start_state_max_bounds_error: 0.1
    jiggle_fraction: 0.05
    max_sampling_attempts: 1000
    
  chomp:
    planning_plugin: chomp_interface/CHOMPPlanner
    request_adapters:
      - default_planner_request_adapters/ResolveConstraintFrames
      - default_planner_request_adapters/ValidateWorkspaceBounds
      - default_planner_request_adapters/CheckStartStateBounds
      - default_planner_request_adapters/CheckStartStateCollision
      - default_planner_request_adapters/FixWorkspaceBounds
      - default_planner_request_adapters/FixStartStateBounds
      - default_planner_request_adapters/FixStartStateCollision
      - default_planner_request_adapters/AddTimeOptimalParameterization
    start_state_max_bounds_error: 0.1
    
  pilz_industrial_motion_planner:
    planning_plugin: pilz_industrial_motion_planner/CommandPlanner
    request_adapters:
      - default_planner_request_adapters/ResolveConstraintFrames
      - default_planner_request_adapters/ValidateWorkspaceBounds
      - default_planner_request_adapters/CheckStartStateBounds
      - default_planner_request_adapters/CheckStartStateCollision
      - default_planner_request_adapters/FixWorkspaceBounds
      - default_planner_request_adapters/FixStartStateBounds
      - default_planner_request_adapters/FixStartStateCollision
      - default_planner_request_adapters/AddTimeOptimalParameterization
    start_state_max_bounds_error: 0.1
