controller_manager:
  ros__parameters:
    update_rate: 5

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
      joints:
        - joint_0
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_7
      command_interfaces:
        - position
        - velocity
      state_interfaces:
        - position
        - velocity

gripper_controller:
  ros__parameters:
    joints:
      - tool_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity